"""
Borderlands Rising - icon table for build_assets_br.py.

Every focus, spirit, decision category and balance-of-power icon the mod
uses, as  key: (game-icons glyph, colour theme)  or, for capstone focuses
that get a laurel ring behind the glyph,  key: (glyph, theme, "capstone").
The frame shape comes from the key's prefix (see FRAMES in the builder).
"""

C = "capstone"

FOCUS = {
    # ------------------------------------------------------------------
    # DANZIG - the Danzig Question
    # ------------------------------------------------------------------
    "DZG_the_danzig_question": ("delapouite/medieval-gate", "dzg_question", C),
    "DZG_lean_on_berlin": ("lorc/eagle-emblem", "dzg_berlin"),
    "DZG_the_westerplatte_question": ("delapouite/military-fort", "dzg_question"),
    "DZG_lean_on_warsaw": ("delapouite/eagle-head", "dzg_warsaw"),
    "DZG_the_corridor_question": ("delapouite/rail-road", "dzg_question"),
    "DZG_break_the_customs_union": ("delapouite/stamper", "dzg_question"),
    "DZG_memel_free_port_treaty": ("delapouite/harbor-dock", "dzg_question"),
    "DZG_the_kashubian_question": ("delapouite/village", "dzg_question"),
    "DZG_the_vistula_delta": ("delapouite/river", "dzg_question"),
    "DZG_pomeranian_ambitions": ("lorc/castle", "dzg_question"),
    "DZG_the_polish_post_office": ("delapouite/post-office", "dzg_warsaw"),
    "DZG_baltic_diplomacy": ("delapouite/scroll-quill", "dzg_question"),
    "DZG_kashubian_volunteers": ("delapouite/huts-village", "dzg_question"),
    "DZG_east_prussian_ambitions": ("delapouite/tower-flag", "dzg_berlin"),
    "DZG_rival_of_warsaw": ("delapouite/sword-brandish", "dzg_warsaw"),
    "DZG_seek_a_great_power_patron": ("lorc/globe", "dzg_question"),
    "DZG_rival_of_berlin": ("lorc/crossed-swords", "dzg_berlin"),
    "DZG_integrate_the_new_territories": ("lorc/jigsaw-piece", "dzg_question"),
    "DZG_the_baltic_shield": ("delapouite/ribbon-shield", "dzg_question"),
    "DZG_queen_of_the_vistula": ("lorc/queen-crown", "dzg_question", C),
    # Danzig - army
    "DZG_the_landespolizei": ("andymeneely/police-badge", "army"),
    "DZG_tear_up_the_demilitarisation_clause": ("lorc/broken-tablet", "army"),
    "DZG_the_oppressed_soldiers": ("skoll/breaking-chain", "army", C),
    "DZG_bischofsberg_barracks": ("delapouite/barracks", "army"),
    "DZG_hagelsberg_fortress": ("lorc/locked-fortress", "army"),
    "DZG_citizens_in_arms": ("sbed/rifle", "army"),
    "DZG_oppressed_soldiers_doctrine": ("lorc/mailed-fist", "army"),
    "DZG_street_fighting_doctrine": ("delapouite/brick-wall", "army"),
    "DZG_vistula_pioneers": ("skoll/trench-spade", "army"),
    "DZG_artillery_of_the_bastions": ("quoting/field-gun", "army"),
    "DZG_staff_college": ("delapouite/graduate-cap", "army"),
    "DZG_motorised_police": ("delapouite/police-car", "army"),
    "DZG_armoured_cars_of_the_free_city": ("skoll/apc", "army"),
    "DZG_the_unbreakable_city": ("delapouite/stone-wall", "army"),
    "DZG_veterans_of_the_great_war": ("delapouite/star-medal", "army"),
    "DZG_officer_school_of_langfuhr": ("delapouite/rule-book", "army"),
    "DZG_the_mobile_reserve": ("delapouite/truck", "army"),
    "DZG_army_of_the_free_city": ("lorc/battle-gear", "army", C),
    "DZG_brotherhood_of_the_oppressed": ("lorc/fist", "army"),
    # Danzig - navy
    "DZG_schichau_contracts": ("lorc/cargo-crane", "navy"),
    "DZG_danziger_werft": ("delapouite/ship-bow", "navy"),
    "DZG_coastal_flotilla": ("cathelineau/iron-hulled-warship", "navy"),
    "DZG_neufahrwasser_u_boat_pens": ("delapouite/submarine", "navy"),
    "DZG_minefields_of_the_bay": ("lorc/mine-explosion", "navy"),
    "DZG_baltic_raiders": ("cathelineau/battleship", "navy"),
    "DZG_marine_infantry": ("lorc/anchor", "navy"),
    "DZG_free_city_navy": ("delapouite/ship-wheel", "navy", C),
    # Danzig - air
    "DZG_danziger_luftpost": ("delapouite/paper-plane", "air"),
    "DZG_junkers_licence": ("quoting/biplane", "air"),
    "DZG_langfuhr_fighter_wing": ("skoll/airplane", "air"),
    "DZG_dive_bomber_staffel": ("lorc/bombing-run", "air"),
    "DZG_coastal_patrol_squadron": ("delapouite/binoculars", "air"),
    "DZG_baltic_air_shield": ("lorc/radar-dish", "air", C),
    "DZG_the_bomber_wing": ("lord-berandas/bomber", "air"),
    # Danzig - politics: fascist
    "DZG_the_volkstag_crisis": ("delapouite/split-arrows", "dzg_question"),
    "DZG_greisers_senate": ("delapouite/ancient-columns", "dzg_fascist"),
    "DZG_the_enabling_decree": ("lorc/scroll-unfurled", "dzg_fascist"),
    "DZG_the_senate_police": ("delapouite/police-officer-head", "dzg_fascist"),
    "DZG_purge_the_gau": ("delapouite/handcuffed", "dzg_fascist"),
    "DZG_danzig_first": ("delapouite/star-flag", "dzg_fascist"),
    "DZG_the_corporate_senate": ("lorc/gears", "dzg_fascist"),
    "DZG_the_vistula_doctrine": ("lorc/compass", "dzg_fascist"),
    "DZG_break_with_berlin": ("lorc/broken-shield", "dzg_fascist"),
    "DZG_free_state_youth": ("delapouite/torch", "dzg_fascist"),
    "DZG_the_baltic_axis": ("lorc/arrow-cluster", "dzg_fascist"),
    "DZG_greater_danzig": ("delapouite/castle", "dzg_fascist"),
    "DZG_the_baltic_war_plan": ("lorc/treasure-map", "dzg_fascist"),
    "DZG_the_eastern_march": ("delapouite/horizon-road", "dzg_fascist"),
    "DZG_the_danziger_reich": ("lorc/eagle-emblem", "dzg_fascist", C),
    # Danzig - politics: democratic
    "DZG_the_geneva_appeal": ("lorc/scales", "dzg_democratic"),
    "DZG_lesters_restoration": ("lorc/book-cover", "dzg_democratic"),
    "DZG_free_volkstag_elections": ("delapouite/vote", "dzg_democratic"),
    "DZG_the_brill_coalition": ("delapouite/public-speaker", "dzg_democratic"),
    "DZG_the_stachnik_coalition": ("delapouite/church", "dzg_democratic"),
    "DZG_social_insurance_act": ("delapouite/family-house", "dzg_democratic"),
    "DZG_hanseatic_kontors": ("delapouite/warehouse", "dzg_democratic"),
    "DZG_appeal_to_london_and_paris": ("lorc/envelope", "dzg_democratic"),
    "DZG_league_arbitration": ("lorc/gavel", "dzg_democratic"),
    "DZG_reconciliation_with_warsaw": ("lorc/dove", "dzg_democratic"),
    "DZG_the_leagues_shield": ("delapouite/attached-shield", "dzg_democratic"),
    "DZG_reclaim_the_hansa_ports": ("delapouite/lighthouse", "dzg_democratic"),
    "DZG_the_new_hanseatic_league": ("delapouite/cargo-ship", "dzg_democratic", C),
    "DZG_join_the_democracies": ("delapouite/european-flag", "dzg_democratic"),
    "DZG_the_hanseatic_republic": ("delapouite/greek-temple", "dzg_democratic", C),
    # Danzig - politics: non-aligned
    "DZG_the_senate_of_notables": ("delapouite/round-table", "dzg_nonaligned"),
    "DZG_rauschning_returns": ("lorc/quill-ink", "dzg_nonaligned"),
    "DZG_the_revolution_of_nihilism": ("lorc/book-storm", "dzg_nonaligned"),
    "DZG_neutral_harbour": ("delapouite/wooden-pier", "dzg_nonaligned"),
    "DZG_the_bank_of_danzig": ("delapouite/bank", "dzg_nonaligned"),
    "DZG_armed_neutrality": ("delapouite/shield-opposition", "dzg_nonaligned"),
    "DZG_purchase_the_delta": ("delapouite/coins-pile", "dzg_nonaligned"),
    "DZG_balance_the_giants": ("lorc/life-in-the-balance", "dzg_nonaligned"),
    "DZG_the_neutral_arsenal": ("sbed/ammo-box", "dzg_nonaligned"),
    "DZG_the_free_city_directorate": ("delapouite/office-chair", "dzg_nonaligned"),
    "DZG_the_baltic_switzerland": ("delapouite/swiss-army-knife", "dzg_nonaligned", C),
    # Danzig - politics: monarchist
    "DZG_the_prussian_question": ("delapouite/throne-king", "dzg_monarchist"),
    "DZG_coronation_in_the_marienkirche": ("delapouite/imperial-crown", "dzg_monarchist"),
    "DZG_the_junker_network": ("delapouite/family-tree", "dzg_monarchist"),
    "DZG_order_of_the_black_eagle": ("lorc/medal", "dzg_monarchist"),
    "DZG_the_royal_wedding": ("delapouite/diamond-ring", "dzg_monarchist"),
    "DZG_claim_the_prussian_inheritance": ("delapouite/winged-scepter", "dzg_monarchist"),
    "DZG_royal_prussian_army": ("delapouite/black-knight-helm", "dzg_monarchist"),
    "DZG_the_kings_diplomacy": ("lorc/tied-scroll", "dzg_monarchist"),
    "DZG_restore_the_kingdom_of_prussia": ("lorc/crown", "dzg_monarchist", C),
    "DZG_monarchist_societies_in_the_reich": ("delapouite/knight-banner", "dzg_monarchist"),
    "DZG_the_german_crown": ("delapouite/jewel-crown", "dzg_monarchist", C),
    # Danzig - politics: communist
    "DZG_red_danzig": ("delapouite/hammer-sickle", "dzg_communist"),
    "DZG_the_shipyard_cells": ("lorc/gear-hammer", "dzg_communist"),
    "DZG_the_general_strike": ("skoll/fist", "dzg_communist"),
    "DZG_workers_militia": ("skoll/winchester-rifle", "dzg_communist"),
    "DZG_the_peoples_tribunals": ("delapouite/banging-gavel", "dzg_communist"),
    "DZG_collectivise_the_werder": ("lorc/wheat", "dzg_communist"),
    "DZG_red_sailors": ("delapouite/paddle-steamer", "dzg_communist"),
    "DZG_join_the_comintern": ("lorc/world", "dzg_communist"),
    "DZG_the_baltic_commune": ("delapouite/modern-city", "dzg_communist"),
    "DZG_export_the_revolution": ("delapouite/megaphone", "dzg_communist"),
    "DZG_the_red_baltic_fleet": ("cathelineau/battleship", "dzg_communist"),
    "DZG_the_baltic_socialist_federation": ("delapouite/round-star", "dzg_communist", C),
    # Danzig - economy
    "DZG_the_free_port": ("delapouite/cargo-crate", "economy", C),
    "DZG_expand_the_industrial_quarter": ("delapouite/factory", "economy"),
    "DZG_kaiserhafen_expansion": ("delapouite/crane", "economy"),
    "DZG_gulden_reform": ("delapouite/coins", "economy"),
    "DZG_the_holm_refinery": ("delapouite/barrel", "economy"),
    "DZG_vistula_delta_polders": ("delapouite/windmill", "economy"),
    "DZG_shipyard_expansion": ("lorc/hammer-nails", "economy"),
    "DZG_ostbahn_rail_hub": ("delapouite/steam-locomotive", "economy"),
    "DZG_amber_workshops": ("delapouite/amber-mosquito", "economy"),
    "DZG_zoppot_casino": ("delapouite/dice-six-faces-six", "economy"),
    "DZG_baltic_grain_trade": ("delapouite/grain-bundle", "economy"),
    "DZG_chemical_works": ("lorc/bubbling-flask", "economy"),
    "DZG_heavy_industry_of_the_free_city": ("delapouite/factory-arm", "economy", C),
    "DZG_arms_exports": ("delapouite/wooden-crate", "economy"),
    "DZG_technische_hochschule": ("delapouite/pencil-ruler", "economy"),
    "DZG_neutral_banking": ("delapouite/banknote", "economy"),
    "DZG_electrification_of_the_werder": ("sbed/electric", "economy"),
    "DZG_free_trade_zone": ("delapouite/shop", "economy"),
    "DZG_polytechnic_laboratories": ("lorc/round-bottom-flask", "economy"),
    "DZG_electrical_works": ("lorc/lightning-arc", "economy"),
    "DZG_baltic_trade_hub": ("delapouite/wireframe-globe", "economy"),
    "DZG_free_city_industrial_plan": ("delapouite/chart", "economy"),
    "DZG_institute_of_physics": ("skoll/atom", "economy"),
    # Danzig - society
    "DZG_the_spa_of_zoppot": ("delapouite/bathtub", "society"),
    "DZG_the_waldoper_zoppot": ("delapouite/theater-curtains", "society"),
    "DZG_hold_an_open_air_concert": ("delapouite/musical-notes", "society", C),
    "DZG_the_bayreuth_of_the_north": ("delapouite/musical-score", "society"),
    "DZG_marienkirche_restoration": ("lorc/ringing-bell", "society"),
    "DZG_minority_schools": ("delapouite/school-bag", "society"),
    "DZG_danziger_neueste_nachrichten": ("delapouite/newspaper", "society"),
    "DZG_free_city_citizenship": ("delapouite/passport", "society"),
    "DZG_the_baltic_pearl": ("delapouite/oyster-pearl", "society", C),

    # ------------------------------------------------------------------
    # SOUTH RUSSIA / AZOV UNITED (shield frame)
    # ------------------------------------------------------------------
    "AZV_the_white_fortress": ("lorc/locked-fortress", "azv_politics", C),
    "AZV_the_veterans_union": ("delapouite/star-medal", "azv_politics"),
    "AZV_the_harbin_delegation": ("delapouite/steam-locomotive", "azv_politics"),
    "AZV_the_putnam_millions": ("delapouite/money-stack", "azv_politics"),
    "AZV_young_russia": ("lorc/sunrise", "azv_politics"),
    "AZV_the_white_idea": ("lorc/quill-ink", "azv_politics"),
    "AZV_the_azov_congress": ("delapouite/round-table", "azv_politics"),
    "AZV_march_on_simferopol": ("lorc/tattered-banner", "azv_politics"),
    "AZV_azov_united": ("lorc/eagle-emblem", "azv_politics", C),
    "AZV_the_vozhd_principle": ("delapouite/public-speaker", "azv_politics"),
    "AZV_tatar_accord": ("lorc/tied-scroll", "azv_politics"),
    "AZV_the_militant_state": ("lorc/mailed-fist", "azv_politics"),
    "AZV_cossack_hosts_rise": ("lorc/crossed-sabres", "azv_politics"),
    "AZV_the_azov_littoral": ("lorc/waves", "azv_politics"),
    "AZV_the_white_crusade": ("delapouite/sword-brandish", "azv_politics"),
    "AZV_the_azov_imperium": ("lorc/crown", "azv_politics", C),
    "AZV_armed_forces_of_south_russia": ("lorc/battle-gear", "azv_army", C),
    "AZV_the_perekop_line": ("lorc/barbed-wire", "azv_army"),
    "AZV_the_coloured_divisions": ("delapouite/knight-banner", "azv_army"),
    "AZV_the_cossack_hosts": ("skoll/mounted-knight", "azv_army"),
    "AZV_lessons_of_1920": ("delapouite/rule-book", "azv_army"),
    "AZV_fortify_the_isthmus": ("delapouite/stone-wall", "azv_army"),
    "AZV_sevastopol_fortress": ("delapouite/military-fort", "azv_army"),
    "AZV_the_kornilov_shock_regiments": ("skoll/stick-grenade", "azv_army"),
    "AZV_drozdovsky_discipline": ("delapouite/metal-boot", "azv_army"),
    "AZV_don_cossack_cavalry": ("delapouite/cavalry", "azv_army"),
    "AZV_kuban_plastuns": ("caro-asercion/mountain-climbing", "azv_army"),
    "AZV_the_british_tanks": ("cathelineau/great-war-tank", "azv_army"),
    "AZV_the_artillery_park": ("lorc/cannon", "azv_army"),
    "AZV_the_isthmus_doctrine": ("lorc/compass", "azv_army"),
    "AZV_the_officer_battalions": ("delapouite/graduate-cap", "azv_army"),
    "AZV_the_cossack_charge": ("delapouite/horse-head", "azv_army"),
    "AZV_mechanised_cossacks": ("delapouite/truck", "azv_army"),
    "AZV_slashchovs_war_college": ("delapouite/book-pile", "azv_army"),
    "AZV_total_mobilisation": ("delapouite/megaphone", "azv_army"),
    "AZV_the_wild_division": ("lorc/wolf-howl", "azv_army"),
    "AZV_armoured_spearheads": ("lorc/battle-tank", "azv_army"),
    "AZV_the_kutepov_reforms": ("lorc/gears", "azv_army"),
    "AZV_the_white_guard": ("delapouite/black-knight-helm", "azv_army", C),
    "AZV_the_unstoppable_host": ("lorc/arrow-cluster", "azv_army", C),
    "AZV_the_black_sea_squadron": ("lorc/anchor", "azv_navy"),
    "AZV_refit_the_general_alekseyev": ("cathelineau/battleship", "azv_navy"),
    "AZV_sevastopol_naval_yards": ("lorc/cargo-crane", "azv_navy"),
    "AZV_the_submarine_division": ("delapouite/submarine", "azv_navy"),
    "AZV_destroyer_flotillas": ("cathelineau/iron-hulled-warship", "azv_navy"),
    "AZV_marines_of_the_black_sea": ("lorc/trident", "azv_navy"),
    "AZV_close_the_kerch_strait": ("delapouite/lighthouse", "azv_navy"),
    "AZV_naval_aviation": ("quoting/biplane", "azv_navy"),
    "AZV_masters_of_the_black_sea": ("delapouite/ship-wheel", "azv_navy", C),
    "AZV_the_kacha_flight_school": ("delapouite/plane-pilot", "azv_air"),
    "AZV_fighter_regiments": ("skoll/airplane", "azv_air"),
    "AZV_ground_attack_squadrons": ("lorc/bombing-run", "azv_air"),
    "AZV_bomber_regiments": ("lord-berandas/bomber", "azv_air"),
    "AZV_air_defence_of_the_peninsula": ("pierre-leducq/anti-aircraft-gun", "azv_air"),
    "AZV_the_white_eagles": ("delapouite/eagle-head", "azv_air", C),
    "AZV_the_garrison_economy": ("delapouite/factory", "azv_economy"),
    "AZV_kerch_iron_works": ("lorc/anvil", "azv_economy"),
    "AZV_the_arsenal_of_the_white_cause": ("sbed/ammo-box", "azv_economy", C),
    "AZV_massandra_wine_exports": ("delapouite/wine-bottle", "azv_economy"),
    "AZV_simferopol_industrial_district": ("delapouite/factory-arm", "azv_economy"),
    "AZV_war_industry": ("lorc/gear-hammer", "azv_economy"),
    "AZV_foreign_arms_dealers": ("delapouite/wooden-crate", "azv_economy"),
    "AZV_the_yalta_riviera": ("delapouite/palm-tree", "azv_economy"),
    "AZV_salt_of_the_sivash": ("lorc/salt-shaker", "azv_economy"),
    "AZV_the_garrison_state": ("darkzaitzev/big-gear", "azv_economy"),
    "AZV_emigre_war_bonds": ("delapouite/banknote", "azv_economy"),
    "AZV_the_simferopol_tank_works": ("lorc/tank", "azv_economy"),
    "AZV_the_arsenal_state": ("sbed/rifle", "azv_economy", C),
    "AZV_the_sevastopol_institute": ("lord-berandas/microscope", "azv_economy"),
    "AZV_the_emigration_calls": ("delapouite/passport", "azv_foreign"),
    "AZV_prometheism": ("delapouite/torch", "azv_foreign"),
    "AZV_friendship_with_ankara": ("delapouite/scroll-quill", "azv_foreign"),
    "AZV_approach_berlin": ("lorc/envelope", "azv_foreign"),
    "AZV_the_white_crusade_alliance": ("delapouite/cross-shield", "azv_foreign", C),
    "AZV_join_the_axis": ("lorc/swords-emblem", "azv_foreign"),
    "AZV_crusader_volunteers": ("delapouite/jerusalem-cross", "azv_foreign"),
    "AZV_strike_when_moscow_burns": ("lorc/fire-bomb", "azv_foreign"),
    "AZV_a_new_south_russia": ("lorc/treasure-map", "azv_foreign", C),

    # ------------------------------------------------------------------
    # AZERBAIJAN / ODLAR YURDU (round frame, fire rim)
    # ------------------------------------------------------------------
    "ODL_the_baby_president": ("delapouite/baby-face", "odl_president", C),
    "ODL_the_regency_council": ("delapouite/round-table", "odl_president"),
    "ODL_the_presidential_nursery": ("delapouite/baby-bottle", "odl_president"),
    "ODL_regency_of_the_musavat": ("delapouite/vote", "odl_president"),
    "ODL_regency_of_the_oil_barons": ("delapouite/money-stack", "odl_president"),
    "ODL_regency_of_the_generals": ("delapouite/star-medal", "odl_president"),
    "ODL_first_words": ("lorc/conversation", "odl_president"),
    "ODL_the_national_anthem": ("delapouite/musical-notes", "odl_president"),
    "ODL_womens_suffrage": ("delapouite/public-speaker", "odl_president"),
    "ODL_the_paris_emigres": ("delapouite/newspaper", "odl_president"),
    "ODL_the_war_council": ("lorc/crossed-swords", "odl_president"),
    "ODL_first_steps": ("skoll/footsteps", "odl_president"),
    "ODL_the_opera_of_uzeyir": ("delapouite/theater-curtains", "odl_president"),
    "ODL_the_latin_alphabet": ("lorc/quill-ink", "odl_president"),
    "ODL_the_kindergarten_cabinet": ("sparker/bear-face", "odl_president"),
    "ODL_baku_state_university": ("delapouite/graduate-cap", "odl_president"),
    "ODL_school_days": ("delapouite/school-bag", "odl_president"),
    "ODL_the_president_takes_charge": ("lorc/laurel-crown", "odl_president", C),
    "ODL_the_eternal_flame": ("carl-olsen/flame", "odl_fire", C),
    "ODL_the_national_army": ("lorc/battle-gear", "odl_army", C),
    "ODL_shikhlinskis_artillery": ("lorc/cannon", "odl_army"),
    "ODL_karabakh_mountain_brigades": ("lorc/mountains", "odl_army"),
    "ODL_the_shusha_cavalry": ("delapouite/horse-head", "odl_army"),
    "ODL_wings_of_the_republic": ("delapouite/plane-wing", "odl_army"),
    "ODL_the_military_academy": ("delapouite/rule-book", "odl_army"),
    "ODL_conscription_reform": ("delapouite/megaphone", "odl_army"),
    "ODL_aslanovs_tanks": ("lorc/battle-tank", "odl_army"),
    "ODL_fighter_squadrons": ("skoll/airplane", "odl_army"),
    "ODL_defend_the_absheron": ("delapouite/watchtower", "odl_army"),
    "ODL_mountain_warfare_doctrine": ("caro-asercion/mountain-climbing", "odl_army"),
    "ODL_motorised_cavalry": ("delapouite/jeep", "odl_army"),
    "ODL_close_air_support": ("lorc/bombing-run", "odl_army"),
    "ODL_the_fire_guard": ("lorc/fluffy-flame", "odl_fire", C),
    "ODL_the_oil_republic": ("delapouite/oil-pump", "odl_oil", C),
    "ODL_the_black_city": ("delapouite/factory", "odl_oil"),
    "ODL_the_nobel_legacy": ("delapouite/laurels-trophy", "odl_oil"),
    "ODL_ganja_industry": ("delapouite/factory-arm", "odl_oil"),
    "ODL_railways_of_the_republic": ("delapouite/railway", "odl_oil"),
    "ODL_bibi_heybat_bay": ("delapouite/oil-rig", "odl_oil"),
    "ODL_oil_concessions": ("lorc/scroll-unfurled", "odl_oil"),
    "ODL_the_oil_council": ("delapouite/barrel", "odl_oil"),
    "ODL_the_sumgait_works": ("lorc/bubbling-flask", "odl_oil"),
    "ODL_baku_batumi_pipeline": ("delapouite/pipes", "odl_oil"),
    "ODL_petrochemistry_institute": ("lorc/round-bottom-flask", "odl_oil"),
    "ODL_mingachevir_dam": ("delapouite/dam", "odl_oil"),
    "ODL_caspian_trade": ("delapouite/cargo-ship", "odl_oil"),
    "ODL_the_oil_fund": ("delapouite/piggy-bank", "odl_oil"),
    "ODL_heavy_industry": ("lorc/gear-hammer", "odl_oil"),
    "ODL_oil_capital_of_the_world": ("lorc/globe", "odl_oil", C),
    "ODL_the_republic_abroad": ("delapouite/wireframe-globe", "odl_foreign"),
    "ODL_the_treaty_of_moscow": ("lorc/tied-scroll", "odl_foreign"),
    "ODL_one_nation_two_states": ("lorc/chained-heart", "odl_foreign"),
    "ODL_british_oil_partners": ("delapouite/fuel-tank", "odl_foreign"),
    "ODL_german_engineers": ("lorc/cog", "odl_foreign"),
    "ODL_the_caucasian_house": ("delapouite/house", "odl_foreign"),
    "ODL_the_neutral_caspian": ("delapouite/peace-dove", "odl_foreign"),
    "ODL_turkish_military_mission": ("sbed/rifle", "odl_foreign"),
    "ODL_khasmammadovs_embassy": ("lorc/envelope", "odl_foreign"),
    "ODL_oil_diplomacy": ("delapouite/oil-can", "odl_foreign"),
    "ODL_the_caucasian_legion": ("delapouite/knight-banner", "odl_foreign"),
    "ODL_the_southern_question": ("lorc/compass", "odl_foreign"),
    "ODL_the_tabriz_uprising": ("delapouite/torch", "odl_foreign"),
    "ODL_a_deal_with_tehran": ("delapouite/receive-money", "odl_foreign"),
    "ODL_the_land_of_fire": ("delapouite/fire-shrine", "odl_fire", C),
    "ODL_derbent_and_beyond": ("delapouite/castle", "odl_foreign"),

    # ------------------------------------------------------------------
    # LITHUANIA / PALANMIR (hexagon frame)
    # ------------------------------------------------------------------
    "PLM_a_proposal_from_mr_phiel": ("delapouite/briefcase", "plm_corporate", C),
    "PLM_install_palanmir": ("delapouite/all-seeing-eye", "plm_tech", C),
    "PLM_the_census_of_everything": ("delapouite/database", "plm_tech"),
    "PLM_the_data_ministry": ("delapouite/server-rack", "plm_tech"),
    "PLM_pack_the_fourth_seimas": ("delapouite/greek-temple", "plm_corporate"),
    "PLM_smetonas_dilemma": ("lorc/life-in-the-balance", "plm_corporate"),
    "PLM_the_phiel_administration": ("delapouite/tie", "plm_corporate", C),
    "PLM_wellbeing_is_a_lagging_indicator": ("delapouite/chart", "plm_corporate"),
    "PLM_the_efficiency_decrees": ("lorc/scroll-unfurled", "plm_corporate"),
    "PLM_predictive_policing": ("delapouite/police-target", "plm_corporate"),
    "PLM_the_algorithmic_budget": ("delapouite/calculator", "plm_corporate"),
    "PLM_the_shareholder_state": ("delapouite/pie-chart", "plm_corporate"),
    "PLM_the_technate": ("lorc/cog", "plm_corporate", C),
    "PLM_palanmir_2_0": ("lorc/microchip", "plm_tech"),
    "PLM_the_sensor_network": ("delapouite/mesh-network", "plm_tech"),
    "PLM_predictive_logistics": ("delapouite/truck", "plm_tech"),
    "PLM_the_integration_protocol": ("delapouite/nested-hexagons", "plm_tech", C),
    "PLM_the_punch_card_bureau": ("delapouite/abacus", "plm_tech"),
    "PLM_palanmir_3_0": ("lorc/brain", "plm_tech"),
    "PLM_total_awareness": ("delapouite/cyber-eye", "plm_tech"),
    "PLM_the_all_seeing_stone": ("delapouite/eye-of-horus", "plm_tech", C),
    "PLM_the_kaunas_laboratories": ("lorc/round-bottom-flask", "plm_research", C),
    "PLM_vytautas_magnus_university": ("delapouite/graduate-cap", "plm_research"),
    "PLM_poach_foreign_scientists": ("delapouite/lab-coat", "plm_research"),
    "PLM_the_engineering_faculty": ("delapouite/pencil-ruler", "plm_research"),
    "PLM_calculating_machines": ("lorc/vintage-robot", "plm_research"),
    "PLM_the_radio_laboratory": ("delapouite/radio-tower", "plm_research"),
    "PLM_the_rocket_society": ("lorc/rocket", "plm_research"),
    "PLM_the_research_campus": ("skoll/atom", "plm_research"),
    "PLM_science_over_sentiment": ("lord-berandas/microscope", "plm_research", C),
    "PLM_algorithmic_construction": ("delapouite/crane", "plm_industry", C),
    "PLM_the_klaipeda_works": ("delapouite/ship-bow", "plm_industry"),
    "PLM_the_kaunas_factories": ("delapouite/factory", "plm_industry"),
    "PLM_automated_planning": ("delapouite/road", "plm_industry"),
    "PLM_the_seven_day_week": ("delapouite/calendar", "plm_industry"),
    "PLM_the_concrete_algorithm": ("delapouite/brick-wall", "plm_industry"),
    "PLM_the_industrial_stack": ("delapouite/factory-arm", "plm_industry", C),
    "PLM_the_data_driven_army": ("lorc/battle-gear", "plm_army", C),
    "PLM_predictive_maintenance": ("sbed/wrench", "plm_army"),
    "PLM_signals_intelligence": ("lorc/radar-sweep", "plm_army"),
    "PLM_the_air_wing": ("skoll/airplane", "plm_army"),
    "PLM_algorithmic_doctrine": ("skoll/chess-knight", "plm_army"),
    "PLM_the_riflemens_union": ("sbed/rifle", "plm_army"),
    "PLM_the_client_list": ("delapouite/notebook", "plm_foreign", C),
    "PLM_the_vilnius_question": ("delapouite/watchtower", "plm_foreign"),
    "PLM_memel_data_hub": ("delapouite/lighthouse", "plm_foreign"),
    "PLM_the_baltic_data_union": ("lorc/tied-scroll", "plm_foreign"),
    "PLM_export_palanmir": ("delapouite/cargo-crate", "plm_foreign"),
    "PLM_reclaim_vilnius": ("delapouite/tower-flag", "plm_foreign", C),
    "PLM_the_global_platform": ("lorc/globe", "plm_foreign", C),
}

IDEA = {
    # Danzig
    "DZG_league_protectorate": ("delapouite/attached-shield", "dzg_democratic"),
    "DZG_polish_customs_union": ("delapouite/stamper", "dzg_warsaw"),
    "DZG_polish_partnership": ("lorc/tied-scroll", "dzg_warsaw"),
    "DZG_reich_subsidies": ("delapouite/coins", "dzg_berlin"),
    "DZG_sovereign_port": ("delapouite/lighthouse", "dzg_question"),
    "DZG_polish_credit": ("delapouite/banknote", "dzg_warsaw"),
    "DZG_open_air_concert": ("delapouite/musical-notes", "society"),
    "DZG_baltic_pearl": ("delapouite/oyster-pearl", "society"),
    "DZG_emergency_decree": ("lorc/scroll-unfurled", "dzg_fascist"),
    "DZG_corporate_senate": ("lorc/gears", "dzg_fascist"),
    "DZG_free_state_youth_idea": ("delapouite/torch", "dzg_fascist"),
    "DZG_danziger_reich_spirit": ("lorc/eagle-emblem", "dzg_fascist"),
    "DZG_restored_constitution": ("lorc/book-cover", "dzg_democratic"),
    "DZG_dockworkers_charter": ("lorc/cargo-crane", "dzg_democratic"),
    "DZG_catholic_social_compact": ("delapouite/church", "dzg_democratic"),
    "DZG_social_insurance": ("delapouite/family-house", "dzg_democratic"),
    "DZG_league_shield": ("delapouite/attached-shield", "dzg_democratic"),
    "DZG_hanseatic_spirit": ("delapouite/cargo-ship", "dzg_democratic"),
    "DZG_armed_neutrality_idea": ("delapouite/shield-opposition", "dzg_nonaligned"),
    "DZG_directorate": ("delapouite/office-chair", "dzg_nonaligned"),
    "DZG_gulden_reserves": ("delapouite/coins-pile", "dzg_nonaligned"),
    "DZG_black_eagle_order": ("lorc/medal", "dzg_monarchist"),
    "DZG_royal_prussian_army_idea": ("delapouite/black-knight-helm", "dzg_monarchist"),
    "DZG_kingdom_of_prussia_spirit": ("lorc/crown", "dzg_monarchist"),
    "DZG_free_soviet_city": ("delapouite/hammer-sickle", "dzg_communist"),
    "DZG_collective_werder": ("lorc/wheat", "dzg_communist"),
    "DZG_peoples_tribunals": ("delapouite/banging-gavel", "dzg_communist"),
    "DZG_baltic_commune_spirit": ("delapouite/round-star", "dzg_communist"),
    "DZG_citizens_in_arms_idea": ("sbed/rifle", "army"),
    "DZG_street_fighters": ("delapouite/brick-wall", "army"),
    "DZG_unbreakable_city": ("delapouite/stone-wall", "army"),
    "DZG_army_of_the_free_city_idea": ("lorc/battle-gear", "army"),
    "DZG_baltic_raiders_idea": ("cathelineau/battleship", "navy"),
    "DZG_free_city_navy_idea": ("delapouite/ship-wheel", "navy"),
    "DZG_baltic_air_shield_idea": ("lorc/radar-dish", "air"),
    "DZG_danzig_gulden": ("delapouite/coins", "economy"),
    "DZG_zoppot_casino_idea": ("delapouite/dice-six-faces-six", "economy"),
    "DZG_industrial_plan": ("delapouite/chart", "economy"),
    "DZG_technische_hochschule_idea": ("delapouite/pencil-ruler", "economy"),
    "DZG_queen_of_the_vistula_idea": ("lorc/queen-crown", "dzg_question"),
    # South Russia / Azov United
    "AZV_island_of_crimea": ("delapouite/island", "azv_politics"),
    "AZV_white_army_remnants": ("lorc/tattered-banner", "azv_army"),
    "AZV_white_army_reborn": ("delapouite/knight-banner", "azv_army"),
    "AZV_azov_united_spirit": ("lorc/eagle-emblem", "azv_politics"),
    "AZV_vozhd_principle": ("delapouite/public-speaker", "azv_politics"),
    "AZV_tatar_accord_idea": ("lorc/tied-scroll", "azv_politics"),
    "AZV_militant_state": ("lorc/mailed-fist", "azv_politics"),
    "AZV_azov_imperium": ("lorc/crown", "azv_politics"),
    "AZV_drozdovsky_discipline_idea": ("delapouite/metal-boot", "azv_army"),
    "AZV_isthmus_doctrine": ("skoll/trench-spade", "azv_army"),
    "AZV_cossack_charge": ("delapouite/horse-head", "azv_army"),
    "AZV_total_mobilisation_idea": ("delapouite/megaphone", "azv_army"),
    "AZV_white_guard": ("delapouite/black-knight-helm", "azv_army"),
    "AZV_black_sea_masters": ("delapouite/ship-wheel", "azv_navy"),
    "AZV_white_eagles": ("delapouite/eagle-head", "azv_air"),
    "AZV_garrison_state_economy": ("darkzaitzev/big-gear", "azv_economy"),
    "AZV_arsenal_state": ("sbed/ammo-box", "azv_economy"),
    "AZV_crusaders": ("delapouite/jerusalem-cross", "azv_foreign"),
    # Azerbaijan
    "ODL_regency_council": ("delapouite/round-table", "odl_president"),
    "ODL_regency_musavat": ("delapouite/vote", "odl_president"),
    "ODL_regency_oil_barons": ("delapouite/money-stack", "odl_oil"),
    "ODL_regency_generals": ("delapouite/star-medal", "odl_army"),
    "ODL_presidential_rule": ("lorc/laurel-crown", "odl_president"),
    "ODL_presidential_nursery": ("delapouite/baby-bottle", "odl_president"),
    "ODL_latin_alphabet": ("lorc/quill-ink", "odl_president"),
    "ODL_the_eternal_flame_idea": ("carl-olsen/flame", "odl_fire"),
    "ODL_black_gold": ("delapouite/oil-pump", "odl_oil"),
    "ODL_oil_wealth": ("delapouite/oil-rig", "odl_oil"),
    "ODL_oil_fund": ("delapouite/piggy-bank", "odl_oil"),
    "ODL_national_army": ("lorc/battle-gear", "odl_army"),
    "ODL_fire_guard": ("lorc/fluffy-flame", "odl_fire"),
    "ODL_neutral_caspian": ("delapouite/peace-dove", "odl_foreign"),
    "ODL_land_of_fire": ("delapouite/fire-shrine", "odl_fire"),
    # Lithuania / Palanmir
    "PLM_palanmir": ("delapouite/all-seeing-eye", "plm_tech"),
    "PLM_lagging_indicator": ("delapouite/chart", "plm_corporate"),
    "PLM_efficiency_decrees": ("lorc/scroll-unfurled", "plm_corporate"),
    "PLM_predictive_policing_idea": ("delapouite/police-target", "plm_corporate"),
    "PLM_algorithmic_budget": ("delapouite/calculator", "plm_corporate"),
    "PLM_shareholder_state": ("delapouite/pie-chart", "plm_corporate"),
    "PLM_the_technate_idea": ("lorc/cog", "plm_corporate"),
    "PLM_science_over_sentiment_idea": ("lord-berandas/microscope", "plm_research"),
    "PLM_algorithmic_construction_idea": ("delapouite/crane", "plm_industry"),
    "PLM_concrete_algorithm": ("delapouite/brick-wall", "plm_industry"),
    "PLM_seven_day_week": ("delapouite/calendar", "plm_industry"),
    "PLM_data_driven_army_idea": ("lorc/battle-gear", "plm_army"),
    "PLM_riflemens_union": ("sbed/rifle", "plm_army"),
    # Kurdistan (state modifiers)
    "KRD_kurdish_resistance": ("lorc/mountains", "krd"),
    "KRD_kurdish_autonomy": ("caro-asercion/heraldic-sun", "krd"),
}

CATEGORY = {
    "DZG_danzig_question": ("delapouite/medieval-gate", "dzg_question"),
    "DZG_claims": ("delapouite/tower-flag", "dzg_question"),
    "DZG_forster": ("lorc/cloak-dagger", "dzg_fascist"),
    "DZG_hansa": ("delapouite/warehouse", "dzg_democratic"),
    "DZG_harbour": ("delapouite/wooden-pier", "dzg_nonaligned"),
    "DZG_crown": ("lorc/crown", "dzg_monarchist"),
    "DZG_red": ("delapouite/hammer-sickle", "dzg_communist"),
    "DZG_free_port": ("delapouite/dice-six-faces-six", "economy"),
    "AZV_arsenal": ("sbed/ammo-box", "azv_economy"),
    "AZV_azov_union": ("delapouite/star-medal", "azv_politics"),
    "AZV_crusade": ("delapouite/cross-shield", "azv_foreign"),
    "ODL_president": ("delapouite/baby-face", "odl_president"),
    "ODL_oil": ("delapouite/oil-pump", "odl_oil"),
    "ODL_southern": ("lorc/compass", "odl_foreign"),
    "ODL_odlar_yurdu": ("carl-olsen/flame", "odl_fire"),
    "PLM_palanmir": ("delapouite/all-seeing-eye", "plm_tech"),
    "KRD_kurdish_question": ("lorc/mountains", "krd"),
}

# Balance of power sides use focus-sized badges.
BOP = {
    "DZG_berlin_side": ("lorc/eagle-emblem", "dzg_berlin"),
    "DZG_warsaw_side": ("delapouite/eagle-head", "dzg_warsaw"),
}
